version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "5173:5173"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
